name: build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-win:
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel build
    - name: Install
      run: pip install .
    - name: Build
      run: python -m build
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test/ --ignore-glob "*benchmark*"
    - name: Upload wheels
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

  build-and-test-ubu:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel build
    - name: Install
      run: pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test/ --ignore-glob "*benchmark*"

  build-and-test-macos:
    runs-on: [macos-latest]
    strategy:
      matrix:
        python-version: ['3.12']
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel build
    - name: Install
      run: pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test/ --ignore-glob "*benchmark*"
